import type { Metadata } from 'next'
import { Geist, Geist_Mono, Sansation } from 'next/font/google'
import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Sansation({
  weight: ['300', '400', '700'],
})

export const metadata: Metadata = {
  title: 'CALTAX by Shyam',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.className} antialiased `}
      >
        {children}
      </body>
    </html>
  )
}
